# Generated by Django 5.2.6 on 2025-09-30 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='longitud',
        ),
    ]
