# Generated by Django 5.2.6 on 2025-10-08 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_registropublico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registropublico',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_publicos', to='eventos.evento'),
        ),
    ]
